export const enumTypeColors: { name: string, value: string }[] = [
    {name: 'red-1', value: 'red-1'},
    {name: 'red-2', value: 'red-2'},
    {name: 'red-3', value: 'red-3'},
    {name: 'yellow-1', value: 'yellow-1'},
    {name: 'yellow-2', value: 'yellow-2'},
    {name: 'yellow-3', value: 'yellow-3'},
    {name: 'orange-1', value: 'orange-1'},
    {name: 'orange-2', value: 'orange-2'},
    {name: 'orange-3', value: 'orange-3'},
    {name: 'green-1', value: 'green-1'},
    {name: 'green-2', value: 'green-2'},
    {name: 'green-3', value: 'green-3'},
    {name: 'theme-teal-1', value: 'theme-teal-1'},
    {name: 'theme-teal-2', value: 'theme-teal-2'},
    {name: 'theme-teal-3', value: 'theme-teal-3'},
    {name: 'indigo-1', value: 'indigo-1'},
    {name: 'indigo-2', value: 'indigo-2'},
    {name: 'indigo-3', value: 'indigo-3'},
    {name: 'theme-blue-1', value: 'theme-blue-1'},
    {name: 'theme-blue-2', value: 'theme-blue-2'},
    {name: 'theme-blue-3', value: 'theme-blue-3'},
    {name: 'gray-1', value: 'gray-1'},
    {name: 'gray-2', value: 'gray-2'},
    {name: 'gray-3', value: 'gray-3'},
    {name: 'gray-4', value: 'gray-4'},
]